const endpoints = Object.freeze({
  CO: { name: 'Colorado DOT Traffic Counts', url: 'https://services.arcgis.com/Vr4pJuhEJB9F4bUA/arcgis/rest/services/COHighway_traffic_MJS/FeatureServer/0/query', fields: ['ROUTE', 'AADT', 'AADTYR', 'FID'] },
  NV: { name: 'Nevada DOT HPMS AADT', url: 'https://gis.dot.nv.gov/rhgis/rest/services/RWS/HPMSOverlay/FeatureServer/0/query', fields: ['RouteName', 'AADT', 'RouteID', 'BeginPoint', 'EndPoint'] },
  AZ: { name: 'Arizona DOT 2024 AADT', url: 'https://services6.arcgis.com/clPWQMwZfdWn4MQZ/arcgis/rest/services/ADOT_2024_Average_Annual_Daily_Traffic_%28AADT%29/FeatureServer/0/query', fields: ['RouteId', 'AADT', 'SubmittalYear', 'SourceDataset'] },
  OR: { name: 'Oregon DOT Traffic Flow AADT', url: 'https://gis.odot.state.or.us/arcgis1006/rest/services/ames/ames/MapServer/7/query', fields: ['HWYNUMB', 'AADT', 'SITE_ID', 'EFFECTV_DT'] },
  ID: { name: 'Idaho Transportation Department AADT', url: 'https://gisportalp.itd.idaho.gov/lrs/rest/services/RHGeneralService/MapServer/1/query', fields: ['RouteID', 'AADT_Default', 'AADTYear', 'OBJECTID'], where: 'AADT_Default > 0', orderByFields: 'AADT_Default DESC' },
});
const bboxFor = (latitude, longitude, radiusMiles = 1) => { const latDelta = radiusMiles / 69; const lonDelta = radiusMiles / (69 * Math.max(0.1, Math.cos(Number(latitude) * Math.PI / 180))); return [Number(longitude) - lonDelta, Number(latitude) - latDelta, Number(longitude) + lonDelta, Number(latitude) + latDelta]; };
const sourceFor = state => endpoints[String(state || '').toUpperCase()] || null;
export const fetchRegionalTraffic = async ({ state, latitude, longitude, radiusMiles = 1 } = {}, { fetchImpl = globalThis.fetch, retrievedAt = new Date().toISOString() } = {}) => {
  const source = sourceFor(state); if (!source) throw new Error('No configured regional traffic endpoint.');
  if (!Number.isFinite(Number(latitude)) || !Number.isFinite(Number(longitude))) throw new Error('Valid latitude and longitude are required.');
  const [west, south, east, north] = bboxFor(latitude, longitude, radiusMiles);
  const params = new URLSearchParams({ f: 'json', where: source.where || 'AADT > 0', outFields: source.fields.join(','), orderByFields: source.orderByFields || 'AADT DESC', returnGeometry: 'false', geometry: `${west},${south},${east},${north}`, geometryType: 'esriGeometryEnvelope', inSR: '4326', spatialRel: 'esriSpatialRelIntersects', resultRecordCount: '25' });
  const response = await fetchImpl(`${source.url}?${params}`); if (!response.ok) throw new Error(`Regional traffic request failed (${response.status}).`);
  const features = (await response.json())?.features || []; const item = features.filter(feature => Number(feature?.attributes?.AADT ?? feature?.attributes?.AADT_Default) > 0).sort((a, b) => Number(b.attributes.AADTYR || b.attributes.UPDATEYR || b.attributes.SubmittalYear || b.attributes.Year_ || b.attributes.AADTYear || String(b.attributes.EFFECTV_DT || '').slice(0, 4) || 0) - Number(a.attributes.AADTYR || a.attributes.UPDATEYR || a.attributes.SubmittalYear || a.attributes.Year_ || a.attributes.AADTYear || String(a.attributes.EFFECTV_DT || '').slice(0, 4) || 0))[0]; if (!item) throw new Error('No nearby AADT segment was returned.'); const attributes = item.attributes;
  return { source: source.name, sourceState: String(state).toUpperCase(), sourceUrl: source.url, sourceRecordId: String(attributes.COUNTSTATIONID || attributes.RouteID || attributes.RID || attributes.SITE_ID || attributes.OBJECTID || ''), roadName: attributes.ROUTE || attributes.RouteName || attributes.Route || attributes.HWYNUMB || attributes.RouteID || null, aadt: Number(attributes.AADT || attributes.AADT_Default), dataYear: Number(attributes.AADTYR || attributes.UPDATEYR || attributes.SubmittalYear || attributes.Year_ || attributes.AADTYear || String(attributes.EFFECTV_DT || '').slice(0, 4) || new Date(retrievedAt).getUTCFullYear()) || null, retrievedAt };
};
