(function () {
  const page = document.querySelector('#adminToolsPage');
  const grid = document.querySelector('#adminSourceGrid');
  const status = document.querySelector('#adminSourceStatus');
  if (!page || !grid) return;

  const esc = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character]));
  const kneaders = { latitude: 40.333002, longitude: -111.712338 };
  const json = path => fetch(path, { cache: 'no-store' }).then(response => { if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json(); });
  const sources = [
    { id: 'nlr', name: 'NLR / AFDC', kind: 'LIVE INVENTORY', description: 'Nearby station locations, brands, ports, power, connectors, access, and published status.', detail: '10-mile production lookup', load: async () => { const response = await fetch(`https://us-central1-bidwise-production.cloudfunctions.net/nlrStations?latitude=${kneaders.latitude}&longitude=${kneaders.longitude}&radius=10`, { cache: 'no-store' }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data = await response.json(); const rows = (data.stations || []).slice(0, 5).map(station => ({ name: station.name, network: station.network, distanceMiles: station.distanceMiles, ports: station.portCount, chargingType: station.chargingType, maxPowerKw: station.maxPowerKw, status: station.status, access: station.access })); return { status: 'ready', detail: `${data.stations?.length || 0} stations returned · retrieved ${data.retrievedAt || 'unknown'}`, rows }; } },
    { id: 'udot', name: 'UDOT AADT', kind: 'VERIFIED SNAPSHOT', description: 'Road-segment traffic for the actual road serving the property.', detail: 'SR 89 Orem · 2024', load: async () => { const data = await json('udot-aadt-data.json'); return { status: 'ready', detail: `${Number(data.aadt).toLocaleString()} vehicles/day · ${data.roadName} · ${data.dataYear}`, rows: [{ segmentId: data.segmentId, road: data.roadName, aadt: data.aadt, dataYear: data.dataYear, reviewer: data.reviewer }] }; } },
    { id: 'registrations', name: 'Utah EV registrations', kind: 'VERIFIED SNAPSHOT', description: 'Annual electric-vehicle registrations used for local EV-growth context.', detail: 'Utah · 2026', load: async () => { const data = await json('utah-ev-registrations-data.json'); return { status: 'ready', detail: `${Number(data.count).toLocaleString()} ${data.fuelType.toLowerCase()} registrations · ${data.observationDate}`, rows: [{ geography: data.geography, year: data.registrationYear, fuelType: data.fuelType, count: data.count, observationDate: data.observationDate }] }; } },
    { id: 'overture', name: 'Overture Maps Places', kind: 'VERIFIED SNAPSHOT', description: 'Nearby food-and-drink places used for the amenity context.', detail: '1 km radius · release 2026-08-19.0', load: async () => { const data = await json('overture-places-data.json'); return { status: 'ready', detail: `${data.foodAndDrinkPlaceCountWithinRadius} food-and-drink places · ${data.placeCountWithinRadius} total places`, rows: (data.samples || []).map(place => ({ name: place.name, category: place.category, address: place.address, confidence: place.confidence, operatingStatus: place.operatingStatus })) }; } },
    { id: 'osm', name: 'OpenStreetMap Overpass', kind: 'CONTINGENCY SNAPSHOT', description: 'Supplementary POI source used only when Overture is unavailable.', detail: 'Fallback only · never combined with Overture', load: async () => { const data = await json('osm-overpass-data.json'); return { status: 'ready', detail: `${data.foodAndDrinkPlaceCountWithinRadius} food-and-drink POIs · ${data.poiCountWithinRadius} total POIs`, rows: (data.samples || []).map(place => ({ id: place.sourceRecordId, name: place.name, type: place.poiType, address: place.address, openingHours: place.openingHours })) }; } },
    { id: 'dealership-gaps', name: 'Car dealerships without EV chargers', kind: 'MAP LAYER', description: 'OSM car dealerships filtered against the NLR/AFDC inventory to highlight sites without a nearby public charger.', detail: '0.25-mile charger exclusion · 10-mile Kneaders radius', load: async () => { const data = await json('car-dealerships-without-ev-chargers-data.json'); return { status: data.status === 'ready' ? 'ready' : 'pending', detail: `${data.records?.length || 0} qualifying places · retrieved ${data.retrievedAt || 'unknown'}`, rows: (data.records || []).slice(0, 5).map(place => ({ name: place.name, address: place.address, latitude: place.latitude, longitude: place.longitude, sourceRecordId: place.sourceRecordId })) }; } },
    { id: 'apartment-gaps', name: 'Apartment complexes without chargers', kind: 'MAP LAYER', description: 'OSM apartment places filtered against the NLR/AFDC inventory to highlight nearby residential charging gaps.', detail: '0.25-mile charger exclusion · 10-mile Kneaders radius', load: async () => { const data = await json('apartment-complexes-without-chargers-data.json'); return { status: data.status === 'ready' ? 'ready' : 'pending', detail: `${data.records?.length || 0} qualifying places · retrieved ${data.retrievedAt || 'unknown'}`, rows: (data.records || []).slice(0, 5).map(place => ({ name: place.name, address: place.address, latitude: place.latitude, longitude: place.longitude, sourceRecordId: place.sourceRecordId })) }; } },
    { id: 'regional', name: 'Regional coverage: CO / NV / AZ / OR / ID', kind: 'LIVE REGIONAL IMPORT', description: 'Official state transportation sources for roadway AADT, paired with U.S. DOE AFDC vehicle-registration context. Colorado and Nevada are first in line.', detail: 'Five-state live AADT function', load: async () => { const data = await json('regional-data-sources.json'); return { status: 'ready', detail: data.implementationStatus, rows: (data.states || []).map(item => ({ priority: item.priority, state: item.state, status: item.status, trafficSource: item.traffic.name, trafficUrl: item.traffic.url, evRegistrationSource: item.evRegistrations.name, proposalUse: item.proposalUse })) }; } },
    { id: 'observed', name: 'Observed charging sessions', kind: 'PROPOSAL INPUT', description: 'Proposal-specific observed market evidence used to establish the current demand anchor.', detail: 'Kneaders reference observation', load: async () => ({ status: 'ready', detail: '17,679 market-proof visits · 12 complete weeks', rows: [{ metric: 'Market-proof visits', value: 17679, observationWindow: '12 complete weeks', note: 'Proposal-supplied observation; not a live feed' }] }) },
    { id: 'rmp-rates', name: 'Rocky Mountain Power Utah tariffs', kind: 'VERIFIED PUBLIC SOURCE', description: 'Published Schedule 6 energy, demand, facilities, and customer charges used to replace the EV energy-cost assumption.', detail: 'Schedule 6 · effective Jan 1, 2026', load: async () => { const data = await json('rocky-mountain-power-utah-rates.json'); return { status: 'ready', detail: `${data.tariff} · effective ${data.effectiveDate}`, rows: [{ summerEnergyRatePerKwh: data.energyRatesPerKwh.summerJuneThroughSeptember, winterEnergyRatePerKwh: data.energyRatesPerKwh.winterOctoberThroughMay, summerDemandRatePerKwMonth: data.demandRatesPerKwMonth.summerJuneThroughSeptember, winterDemandRatePerKwMonth: data.demandRatesPerKwMonth.winterOctoberThroughMay, annualWeightedEnergyRatePerKwh: data.annualWeightedEnergyRatePerKwh, source: data.rateSummaryUrl }] }; } },
    { id: 'ocpi', name: 'OCPI network status', kind: 'WAITING FOR ACCESS', description: 'Live EVSE/connector availability and status-change timestamps.', detail: 'Adapter ready · provider endpoint/token not configured', load: async () => ({ status: 'pending', detail: 'No participating network credentials configured', rows: [] }) },
    { id: 'paren', name: 'Paren performance data', kind: 'ACCESS REQUESTED', description: 'Licensed utilization, reliability, availability, pricing, and session-performance data.', detail: 'Private-beta request submitted 2026-08-26', load: async () => ({ status: 'pending', detail: 'Awaiting approved API or licensed file access', rows: [] }) },
    { id: 'tesla', name: 'Tesla Fleet API', kind: 'EVALUATED · NOT SUITABLE', description: 'Official Tesla API reviewed for public charger pricing and utilization.', detail: 'Vehicle/fleet-scoped API; no public nationwide station-utilization endpoint', load: async () => ({ status: 'not-applicable', detail: 'Not connected: no public proposal dataset is provided', rows: [] }) },
  ];
  sources.find(source => source.id === 'tesla').load = async () => ({ status: 'error', detail: 'Not connected: Tesla does not provide the public proposal dataset we need', rows: [] });
  const examples = { nlr: 'Examples: charger count · DC-fast vs Level 2 · network brand · operating status', udot: 'Examples: vehicles/day · road segment · data year · traffic exposure', registrations: 'Examples: EV count · county/geography · registration year · growth context', overture: 'Examples: restaurants · cafes · nearby competitors · place confidence', osm: 'Examples: POI names · restaurants · addresses · opening hours', 'dealership-gaps': 'Examples: dealership name · address · charger-gap status · map location', 'apartment-gaps': 'Examples: complex name · address · charger-gap status · map location', regional: 'Examples: CO AADT · NV AADT · AZ AADT · OR/ID AADT · AFDC EV registrations', observed: 'Examples: visits/day · session window · market proof · demand anchor', 'rmp-rates': 'Examples: summer energy rate · winter energy rate · demand charge · customer charge', ocpi: 'Examples: available ports · occupied ports · connector status · last update', paren: 'Examples: utilization rate · sessions/port/day · reliability · historical trend', tesla: 'Examples: vehicle charging history · fleet sessions · billed amount · energy delivered' };
  const verifiedKey = 'getev-admin-source-verification';
  const verifiedDates = (() => { try { return JSON.parse(localStorage.getItem(verifiedKey) || '{}'); } catch { return {}; } })();
  const initialResult = source => ({ status: source.id === 'tesla' ? 'error' : source.id === 'paren' || source.id === 'ocpi' ? 'pending' : 'unchecked', detail: source.detail, rows: [], verifiedAt: verifiedDates[source.id] || null });
  const verificationLabel = result => result.verifiedAt ? `Verified on ${new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric' }).format(new Date(result.verifiedAt))}` : result.status === 'unchecked' ? 'Not checked' : result.status.replace('-', ' ');
  const table = rows => { if (!rows?.length) return '<p class="admin-no-sample">No sample rows available for this source.</p>'; const columns = [...new Set(rows.flatMap(row => Object.keys(row)))]; return `<div class="admin-sample-table-wrap"><table class="admin-sample-table"><thead><tr>${columns.map(column => `<th>${esc(column)}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${columns.map(column => `<td>${esc(row[column] ?? '—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; };
  const card = (source, result) => `<article class="admin-source-card is-${esc(result.status)}" data-source-card="${esc(source.id)}"><div class="admin-source-card-head"><div><div class="admin-source-kind">${esc(source.kind)}</div><h3>${esc(source.name)}</h3></div><span class="admin-source-status-chip">${esc(verificationLabel(result))}</span></div><p>${esc(source.description)}</p><small class="admin-source-examples">${esc(examples[source.id] || '')}</small><small class="admin-source-detail">${esc(result.detail)}</small><button class="admin-sample-button" type="button" data-source-sample="${esc(source.id)}">Get Sample Data</button><div class="admin-source-sample" data-source-sample-output="${esc(source.id)}" hidden></div></article>`;
  let results = Object.fromEntries(sources.map(source => [source.id, initialResult(source)]));
  const bindSamples = () => grid.querySelectorAll('[data-source-sample]').forEach(button => button.addEventListener('click', async () => { const source = sources.find(item => item.id === button.dataset.sourceSample); const output = grid.querySelector(`[data-source-sample-output="${source.id}"]`); button.disabled = true; button.textContent = 'Loading…'; output.hidden = false; output.innerHTML = '<p class="admin-no-sample">Retrieving sample data…</p>'; try { results[source.id] = await source.load(); if (results[source.id].status === 'ready') { results[source.id].verifiedAt = new Date().toISOString(); verifiedDates[source.id] = results[source.id].verifiedAt; localStorage.setItem(verifiedKey, JSON.stringify(verifiedDates)); } const sourceCard = grid.querySelector(`[data-source-card="${source.id}"]`); sourceCard.outerHTML = card(source, results[source.id]); const refreshed = grid.querySelector(`[data-source-card="${source.id}"]`); const refreshedOutput = refreshed.querySelector(`[data-source-sample-output="${source.id}"]`); refreshedOutput.hidden = false; refreshedOutput.innerHTML = table(results[source.id].rows); refreshed.querySelector('[data-source-sample]').textContent = 'Refresh Sample Data'; status.textContent = `${source.name} checked · ${results[source.id].detail}`; bindSamples(); } catch (error) { results[source.id] = { status: 'error', detail: `Unavailable: ${error.message}`, rows: [] }; const sourceCard = grid.querySelector(`[data-source-card="${source.id}"]`); sourceCard.outerHTML = card(source, results[source.id]); const refreshed = grid.querySelector(`[data-source-card="${source.id}"]`); const refreshedOutput = refreshed.querySelector(`[data-source-sample-output="${source.id}"]`); refreshedOutput.hidden = false; refreshedOutput.innerHTML = `<p class="admin-no-sample">${esc(results[source.id].detail)}</p>`; status.textContent = `${source.name} could not be checked.`; bindSamples(); } }));
  const render = () => { grid.innerHTML = sources.map(source => card(source, results[source.id])).join(''); bindSamples(); };
  render();
  window.addEventListener('getev:identity', event => { if (!event.detail?.isAdmin || !document.body.classList.contains('admin-route')) { page.hidden = true; return; } page.hidden = false; status.textContent = `Signed in as ${event.detail.email}. Select a source to retrieve sample data.`; });
})();
