// Render the approved September proposal changes through the existing state, catalog, and section system.
function reviewHelp(text) { const safe=esc(text); return `<button type="button" class="metric-help" aria-label="How this is calculated" data-help="${safe}" title="${safe}">?</button>`; }
function reviewMoney(value, digits=0) { return Number(value).toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:digits,maximumFractionDigits:digits}); }
function reviewMetric(label,value,note='',help='',className='') { return `<article class="review-metric ${className}"><span>${esc(label)} ${help ? reviewHelp(help):''}</span><strong>${value}</strong><small>${note}</small></article>`; }
function reviewRange(values) { return values.map(v=>reviewMoney(v)).join('–'); }
function reviewSection(id,label,title,subtitle,body,className='') { return `<section id="${id}" class="ev-report-section ${className}" data-nav-label="${esc(label)}"><div class="ev-report-head"><div><span class="chart-label">${esc(label.toUpperCase())}</span><h3>${title}</h3></div>${subtitle ? `<p>${subtitle}</p>`:''}</div>${body}</section>`; }
function renderReviewedProposal(section) {
  const retainedLayoutTool=$('#evLayoutToolMount .layout-tool') || $('#layout .layout-tool');
  const config=cardCatalog('ev.review',{}), model=GetEVProposalModel.evaluate(state,config), ranges=GetEVProposalModel.ranges(state,config);
  const host=esc(state.overview.siteName), installer=esc(state.brand.companyName || 'Installer');
  const city=esc(state.overview.city || state.overview.location.split(',').map(s=>s.trim())[1] || 'this area');
  const registeredInstaller=state.brand.companyName && !/1solar/i.test(state.brand.companyName);
  const about=cardCatalog('ev.referencePages.about',{});
  const heading=(label,help)=>`${esc(label)} ${reviewHelp(help)}`;
  const money=reviewMoney;
  const row=(label,value,note='')=>`<div class="review-row"><span>${label}</span><b>${value}</b>${note?`<small>${note}</small>`:''}</div>`;
  const benchmark=config.roadBenchmark;
  const isUtah=/\b(UT|Utah)\b/i.test(state.overview.location);
  const roadMean=benchmark?.mean || 12749.02471025585;
  const statePeak=Number(benchmark?.maximum||214000), statePeakCity=benchmark?.city||'Salt Lake City', statePeakRoad=benchmark?.road||'I-15 at 500/600 South';
  const roadLabel=state.ev.dailyTraffic>=roadMean*2?'WAY ABOVE AVERAGE':state.ev.dailyTraffic>=roadMean*1.1?'ABOVE AVERAGE':'AVERAGE';
  const roadExplanation=isUtah?`UDOT 2024 mean: ${number(roadMean)} vehicles/day. State peak: ${number(statePeak)} on ${statePeakRoad}, ${statePeakCity}.`:'A verified statewide comparison is not available for this location.';
  const referenceNearby=Math.abs(state.site.latitude-40.333002)<.15 && Math.abs(state.site.longitude+111.712338)<.15;
  const location=`<div class="ev-location-metrics"></div><div class="ev-market-grid location-market-grid"><div class="ev-market-map-wrap"><div id="evMarketMap" class="map-card ev-market-map"></div></div><aside class="ev-panel ev-market-proof location-market-proof"><span class="chart-label">OBSERVED MARKET EVIDENCE</span><h4>${referenceNearby?'Orem has proven fast-charging demand.':'Local charging context'}</h4><p>${referenceNearby?`A nearby ${number(state.ev.marketProofPorts)}-port station recorded ${number(state.ev.marketProofSessions3m)} successful sessions over ${number(state.ev.marketProofDays)} days — approximately ${number(state.ev.marketProofSessions3m/state.ev.marketProofDays)} visits per day.`:'Charging inventory is shown on the map. Observed session evidence must be confirmed for this location.'}</p></aside></div><div class="ev-location-support">${reviewMetric('ROADWAY EXPOSURE',`${number(state.ev.dailyTraffic)} VEHICLES / DAY`,isUtah?`${roadLabel} · ${number(state.ev.dailyTraffic/statePeak*100,1)}% OF ${statePeakCity.toUpperCase()} STATE PEAK`:'STATE COMPARISON PENDING',roadExplanation)}${reviewMetric('HIGHWAY ACCESS',`${number(state.ev.travelRouteDistance,1)} MI TO EXIT`,'Shorter distances improve corridor convenience.','Distance from the proposed site to a major highway exit; verify driving access with the property plan.')}${reviewMetric('BUSINESS HOURS',/kneaders/i.test(state.overview.siteName)?'MON–SAT 7 AM–10 PM':'HOURS TO CONFIRM',/kneaders/i.test(state.overview.siteName)?'Sunday closed':'Confirm hours with the business.','Published business hours can be obtained from business websites and OpenStreetMap when available.')}</div>${isUtah?`<p class="review-benchmark">${number(state.ev.dailyTraffic/statePeak*100,1)}% of Utah’s state peak — ${number(statePeak)} vehicles/day on ${statePeakRoad}, ${statePeakCity}. ${reviewHelp(`Source: UDOT ${benchmark?.year||2024} AADT.\nScale: average compares this site with the statewide mean; the state peak is the highest documented count, not a sales forecast.`)}</p>`:''}`;
  let site=siteSnapshotMarkup(cardCatalog('ev.siteSnapshotMockup',{}));
  // Preserve default metric selection and IDs; remove the retired amenities card by its catalog key below.
  const aboutBody=`<div class="review-about"><div class="review-about-copy"><img class="review-company-logo" src="${esc(state.brand.companyLogo||'assets/getev-placeholder-logo.svg')}" alt="${installer} logo"><span class="review-about-kicker">CORPORATE PROFILE</span><div class="review-about-fact"><h4>Proven Scale</h4><p>${esc(state.brand.provenScale || (registeredInstaller ? state.brand.tagline || 'Company experience can be added in the company profile.' : about.cards?.[0]?.[2] || 'Company experience can be added in the company profile.'))}</p></div><div class="review-about-fact"><h4>Licensed &amp; Certified</h4><p>${esc(state.brand.proposalCertifications || (registeredInstaller ? 'Add current credentials in the company profile.' : about.cards?.[1]?.[2] || 'Add current credentials in the company profile.'))}</p></div></div><div class="review-company-photo">${state.brand.companyPhoto?`<img src="${esc(state.brand.companyPhoto)}" alt="${installer} company project">`:'<span>Company project photo<br><small>Add your photo in Company profile</small></span>'}</div></div>`;
  const equipment=config.equipment || {};
  const equipmentBody=`<div class="review-equipment"><div class="review-panel review-highlight"><span class="chart-label">PROPOSED EQUIPMENT</span><h4>TESLA V4</h4><strong>UP TO 500 kW</strong><img src="${esc(equipment.image || 'assets/tesla-v4-supercharger.webp')}" alt="Tesla V4 Supercharger"><p>V4 cabinet power-sharing supports up to 8 posts.</p></div><div class="review-panel"><span class="chart-label">LEVEL 2 VS. DC FAST CHARGING</span><div class="review-grid">${reviewMetric('LEVEL 2',equipment.level2||'7.6–19.2 kW','Longer stays; homes, workplaces and destinations.')}${reviewMetric('LEVEL 3 / DC FAST',equipment.dcFast||'50–350 kW','Travel corridors and shorter retail visits.')}${reviewMetric('TESLA V4',equipment.v4||'UP TO 500 kW','Maximum hardware capability; actual delivery varies.','','review-highlight')}</div></div><div class="review-panel"><span class="chart-label">ONE LOCATION. TWO DRIVER AUDIENCES.</span><div class="review-two"><div><h4>Tesla drivers</h4><p>Trip Planner and Supercharger discovery help drivers find a charging stop.</p></div><div><h4>Compatible non-Tesla drivers</h4><p>Eligible NACS and CCS1 vehicles can find compatible sites in the Tesla app.</p></div></div><p>Network integration makes the property discoverable as a charging stop.</p></div><div class="review-panel"><h4>Plan capacity around the property.</h4><p>Phase construction around the approved site plan. Reserve utility and civil capacity for future expansion.</p><small>Maximum hardware power is not a promised charging speed. Vehicle, cabinet, load sharing and site conditions determine delivered power.</small></div></div>`;
  const leaseHelp=`GetEV Score ${number(model.getevScore,1)}/10 is the weighted scorecard result. It helps set modeled utilization; lease capacity then subtracts the 12% return hurdle before rounding to $25 per port/month.`;
  const partnershipBody=`<div class="reference-option-grid"><article class="reference-option"><span class="chart-label">OPTION 1</span><h4>${installer.toUpperCase()}-OWNED</h4><strong>${money(model.leaseAnnual/12)} / MONTH</strong><b>${heading('PARKING-STALL LEASE INCOME',leaseHelp)}</b><ul><li>${installer} funds, installs, owns and monitors the equipment.</li><li>${model.ports} stalls × ${money(model.leasePerPortMonth)} per port each month.</li><li>${host} receives lease income plus visits from charging guests.</li></ul></article><article class="reference-option"><span class="chart-label">OPTION 2</span><h4>${host.toUpperCase()}-OWNED</h4><strong>100%</strong><b>AVAILABLE CHARGING REVENUE</b><ul><li>${host} funds or finances and owns the equipment.</li><li>The host receives charging revenue and pays the listed station costs.</li><li>${installer} supports design, permitting, installation and monitoring.</li></ul></article></div>`;
  const base=ranges[1], leaseValues=ranges.map(r=>r.annual.map(v=>v+model.leaseAnnual));
  const optionBody=`<div class="review-grid">${reviewMetric('HOST CHARGER INVESTMENT','$0','Installer funds equipment and installation.')}${reviewMetric('PARKING-STALL LEASE',`${money(model.leaseAnnual)} / YEAR`,`${model.ports} ports × ${money(model.leasePerPortMonth)} / month.`,leaseHelp)}${reviewMetric('POTENTIAL GUEST TRAFFIC',`${number(base.parties[0])}–${number(base.parties[1])} PARTIES / DAY`,'Medium guest-capture range from the guest-revenue page.','Daily charging visits × low and high guest-capture bounds.')}</div><div class="review-two"><div class="review-panel"><span class="chart-label">HOW OPTION 1 CREATES NEW REVENUE</span><h4>Lease income plus potential guest sales.</h4>${row(heading('Charging revenue per port / month','Annual driver charging revenue ÷ ports ÷ 12.'),money(model.revenue/model.ports/12))}${row(heading('Your lease per port / month',leaseHelp),money(model.leasePerPortMonth))}${row(heading('Potential annual guest sales','Same capture and ticket ranges as the additional-guests page.'),reviewRange(base.annual))}</div><div class="review-panel review-highlight"><span class="chart-label">MEDIUM GUEST-VALUE CASE</span><strong class="review-big">${reviewRange(leaseValues[1])} / YEAR</strong><p>Potential guest gross sales plus the annual lease.</p><small>Gross guest sales are not restaurant profit.</small></div></div><div class="review-grid">${ranges.map((r,i)=>reviewMetric(['LOW','MEDIUM','HIGH'][i]+' GUEST CASE',reviewRange(leaseValues[i]),`${r.captures.join('–')}% capture · ${reviewRange(r.spends)} spend`, 'Annual lease + daily charging visits × guest capture × party spend × operating days.')).join('')}</div>`;
  const optionTwoBody=`<div class="review-grid">${reviewMetric('CHARGER PROJECT INVESTMENT',money(model.capital),'Upfront equipment and installation contribution.')}${reviewMetric('GROSS CHARGING REVENUE',money(model.revenue),'All modeled charging revenue at the expected case.')}${reviewMetric('CHARGING INCOME AFTER COSTS',money(model.income),'Gross charging revenue less listed station operating costs.')}</div><div class="review-panel review-highlight"><span class="chart-label">HOST-OWNED VALUE</span><h4>${host} owns the station and receives the modeled charging income.</h4>${row(heading('Annual charging income', 'Charging revenue less network, power, operations and payment costs.'),money(model.income))}${row(heading('Potential guest sales', 'The separate Slide 4 guest-sales case is not included in charging income.'),money(calc.evRestaurantSalesAnnual(state.ev.averageReceipt)))}</div>`;
  const dailyRows=model.costs.map(c=>row(c.label,`${money(c.annual/model.days)} / day`)).join('');
  const portEconomicsRows=`${row(heading('Charging income / port / month','Uses the same Year 5 charging visits shown on Slide 4, multiplied by energy and price, then divided across the proposed ports and 12 months.'),money(model.revenue/model.ports/12))}${row(heading('Host share / port / month','The modeled host payment is derived from the same port economics after the return hurdle; the share rate is used in the calculation but not displayed.'),money(model.leasePerPortMonth))}`;
  const perSession=model.costs.map(c=>row(c.label,`(${money(c.annual/(model.sessions*model.days),2)})`)).join('');
  const flow=model.costs.map((c,i)=>`<i style="flex:${Math.max(.01,c.annual)};background:${['#647b8b','#879ca9','#a7b7bf','#ccd6db'][i]}"></i>`).join('')+`<i style="flex:${Math.max(.01,model.income)};background:#b4df62"></i>`;
  const dailyBody=`<div class="reference-ribbon"><b>EXPECTED PLANNING CASE</b><span>${model.ports} PORTS · ${number(model.sessions)} SESSIONS / DAY · ${model.energy} kWh / SESSION · ${money(model.price,2)} / kWh</span></div><div class="review-two"><div class="review-panel"><span class="chart-label">HOW THE DAILY CHARGING REVENUE COULD FLOW</span><h4>${money(model.revenue/model.days)} collected − ${money(model.expenses/model.days)} operating costs = ${money(model.income/model.days)} remains</h4><div class="review-flow" aria-label="Operating costs and remaining charging income">${flow}</div>${dailyRows}${row('Charging income remaining',`${money(model.income/model.days)} / day`)}${portEconomicsRows}<small>Power includes the energy tariff plus a ${number(model.demandCost/12)} dollar monthly demand, facilities and customer allowance.</small></div><div class="review-panel"><span class="chart-label">WHAT ONE DRIVER’S SESSION COULD CREATE</span>${row(`ONE ${model.energy} kWh SESSION`,'AMOUNT')}${row('Driver charging revenue',money(model.energy*model.price,2))}${perSession}${row('Charging income remaining',money(model.income/(model.sessions*model.days),2))}</div></div><div class="review-two">${reviewMetric('WHAT THE INSTALLER PORTION SUPPORTS',`${money(model.costs[2].annual/model.days)} / DAY`,'Monitoring, maintenance oversight, troubleshooting, utility review and site coordination.')}${reviewMetric('WHAT OWNERSHIP COULD LEAVE FOR THE HOST',`${money(model.income/model.days)} / DAY`,'Charging operating income before financing, insurance and tax.')}</div>`;
  const combined=model.income+calc.evRestaurantSalesAnnual(state.ev.averageReceipt);
  const annualBody=`<div class="review-grid">${reviewMetric('CHARGER PROJECT INVESTMENT',money(model.capital),'Upfront charger project capital.')}${reviewMetric('ANNUAL CHARGING INCOME',money(model.income),'After listed station operating costs.')}${reviewMetric('POTENTIAL ANNUAL GUEST SALES',reviewRange(base.annual),'Gross business sales, separate from charger income.')}</div><div class="review-two"><div class="review-panel"><span class="chart-label">YEAR-ONE VALUE AT THE PLANNING RUN RATE</span><h4>${money(combined)} in combined annual value</h4>${row('Driver charging revenue',money(model.revenue))}${row('Listed station operating expenses',`(${money(model.expenses)})`)}${row('Charging income after operating costs',money(model.income))}${row('Potential guest sales (medium midpoint)',money(calc.evRestaurantSalesAnnual(state.ev.averageReceipt)))}</div><div class="review-panel review-highlight"><h4>Ownership results</h4>${row('Charging-only simple payback',model.paybackYears===null?'Not reached':`${number(model.paybackYears,1)} years`)}${row('20-year combined value',money(combined*20))}${row('20-year net value after project cost',money(combined*20-model.capital))}${row('20-year simple value return',`${number((combined*20-model.capital)/Math.max(1,model.capital)*100,1)}%`)}<small>Guest sales are gross sales, not profit. No escalation assumed.</small></div></div><div class="review-panel"><span class="chart-label">CUMULATIVE COMBINED VALUE · NO ESCALATION</span><div class="review-milestones">${[1,5,10,15,20].map(y=>`<div><small>YEAR ${y}</small><strong>${money(combined*y)}</strong><small>Net ${money(combined*y-model.capital)}</small></div>`).join('')}</div></div>`;
  const years=model.paybackYears;
  const cumulative=years===null?'':`<div class="review-two">${reviewMetric('REVENUE THROUGH BREAKEVEN',money(model.revenue*years),'Cumulative driver payments.')}${reviewMetric('EXPENSES THROUGH BREAKEVEN',money(model.expenses*years+model.capital),'Operating expenses plus initial investment.')}</div>`;
  const summary=`<div class="review-panel review-highlight"><span class="chart-label">ANNUAL CHARGING OPERATIONS</span><div class="review-equation">${reviewMetric('REVENUE',money(model.revenue))}<b>−</b>${reviewMetric('EXPENSES',money(model.expenses))}<b>=</b>${reviewMetric('OPERATING PROFIT',money(model.income))}</div></div><div class="review-two">${reviewMetric('INITIAL INVESTMENT',money(model.capital),'Charger project cost; no unrelated solar or battery capital.')}${reviewMetric('ESTIMATED BREAKEVEN',years===null?'NOT REACHED':`${number(years*12,1)} MONTHS`,years===null?'Operating income does not cover the investment.':`${number(years,2)} years from the start of the modeled run rate.`,'Initial investment ÷ annual charging operating profit. Constant utilization; no escalation.')}</div>${cumulative}<div class="review-panel"><h4>Five years after breakeven</h4><div class="review-equation">${reviewMetric('REVENUE',money(model.revenue*5))}<b>−</b>${reviewMetric('EXPENSES',money(model.expenses*5))}<b>=</b>${reviewMetric('OPERATING PROFIT',money(model.income*5))}</div><p>${years===null?'Breakeven is not reached in this scenario.':`This covers years ${number(years,2)}–${number(years+5,2)} after the modeled run rate begins; capital has been recovered at the start of this period.`}</p></div><p class="review-note">Planning forecast at the stated utilization. Excludes financing, insurance, taxes and incentives. Guest gross sales are excluded from profit and breakeven.</p>`;
  section.innerHTML=`<div class="ev-customer-story">${reviewSection('ev-report-1','Location overview','What is already happening around this location.','Observed charging activity, local traffic and access establish the market context.',location,'location-overview-page')}${reviewSection('ev-report-2','Site snapshot','How much charging demand could this site capture?','Fleet growth, charging behavior and property fit inform the planning cases.',site,'site-snapshot-page')}${reviewSection('ev-report-3','Revenue from additional guests','What could additional charging guests mean for business sales?','The ranges vary both guest capture and spending per purchasing party.',visitorRevenueMarkup(cardCatalog('ev.visitorRevenueMockup',{})),'revenue-guests-section')}${reviewSection('ev-report-4',`About ${state.brand.companyName||'the installer'}`,'Proven Scale &amp; Certifications','',aboutBody,'about-1solar-section')}${reviewSection('ev-equipment','What we install',esc(equipment.title||'Tesla V4 fast charging'),esc(equipment.description||''),equipmentBody,'equipment-section')}${reviewSection('ev-report-5','Partnership opportunities','As a Tesla-certified installer, we can do one of two options.','',partnershipBody,'partnership-section')}${reviewSection('ev-report-6',`Option 1 – ${state.brand.companyName||'installer'}-owned`,'Add charging guests with $0 charger investment.',`${installer} owns and operates the station. ${host} receives lease income and potential guest sales.`,optionBody,'option-one-section')}${reviewSection('ev-report-7','Revenue forecast',`${money(model.income/model.days)} in charging income per day.`,`The ${number(model.sessions)}-session planning case, after the operating costs shown below.`,dailyBody,'market-daily-section')}${reviewSection('ev-report-8','Ownership value','Direct charging income plus a guest-sales opportunity.','Keep operating income and potential gross business sales separate.',annualBody,'annual-charging-section')}${reviewSection('ev-report-9','Profit & breakeven','The charging business, at a glance.','',summary,'profit-summary-section')}${reviewSection('ev-construction','Construction site plan','Construction site plan.','Place equipment, draw trenching and striping, and annotate the property.', '<div class="ev-site-layout"><div id="evLayoutToolMount"></div></div>','construction-plan-section')}</div>`;
  const equipmentSection=section.querySelector('#ev-equipment');
  if(equipmentSection){
    const head=equipmentSection.querySelector('.ev-report-head');
    if(head){head.querySelector('h3').textContent='Tesla V4 brings up to 500 kW hardware capability to this site.'; head.querySelector('p').textContent='The proposed four-post first phase combines next-generation DC fast charging with network discovery for Tesla and compatible non-Tesla drivers.';}
    const panels=equipmentSection.querySelectorAll('.review-equipment>.review-panel');
    const strategy=panels[panels.length-1]; if(strategy){strategy.querySelector('h4').textContent='Four posts now. Plan for eight.'; strategy.querySelector('p').textContent='Focused first-post opening configuration with a clear path to future expansion.';}
  }
  // Keep the established report anchors intact for navigation and configuration.
  // Add the host-owned option after the ownership-value page so it remains Slide 9
  // without displacing the revenue forecast or breaking downstream references.
  const ownershipSection=section.querySelector('#ev-report-8');
  if(ownershipSection) ownershipSection.insertAdjacentHTML('afterend',reviewSection('ev-report-7-option-two',`Option 2 – ${state.overview.siteName||'host'}-owned`,'Own the charging station and receive the operating value.','',optionTwoBody,'option-two-section'));
  // Guard against accidental duplicate output if this renderer is extended.
  let dailyHeadingSeen=false;
  section.querySelectorAll('.chart-label').forEach(label=>{if(label.textContent.trim()==='HOW THE DAILY CHARGING REVENUE COULD FLOW'){if(dailyHeadingSeen) label.closest('.review-panel')?.remove(); else dailyHeadingSeen=true;}});
  section.querySelectorAll('.ev-report-section').forEach((node,i)=>{node.querySelector('.ev-report-head .chart-label').textContent=`${String(i+2).padStart(2,'0')} / ${node.dataset.navLabel.toUpperCase()}`;});
  // The reviewed proposal owns the slide sequence in view-only mode. Rebuild the
  // left navigation from the rendered sections so later slides remain reachable.
  const reportNav=$('.report-nav');
  if(reportNav){
    const slides=[...section.querySelectorAll('.ev-report-section')];
    reportNav.innerHTML=slides.map((node,index)=>`<button class="nav-item ${index===0?'active':''}" data-target="${node.id}"><span>${String(index+2).padStart(2,'0')}</span>${esc(node.dataset.navLabel||'Section')}</button>`).join('');
    reportNav.querySelectorAll('[data-target]').forEach(button=>button.addEventListener('click',()=>document.getElementById(button.dataset.target)?.scrollIntoView({behavior:'smooth',block:'start'})));
  }
  const layoutMount=$('#evLayoutToolMount'); if(retainedLayoutTool&&layoutMount)layoutMount.appendChild(retainedLayoutTool);
  $('#layout')?.classList.add('scope-off'); setTimeout(()=>mountLayoutMap(),0);
}
function refreshReviewedDetails() {
  if(!isEvOnlyBid)return;
  const config=cardCatalog('ev.review',{}), model=GetEVProposalModel.evaluate(state,config);
  document.querySelectorAll('.site-fit-items>div').forEach(node=>{if(/NEARBY AMENITIES/.test(node.textContent))node.remove();});
  const outlook=$('#evSnapshotOutlook'); if(outlook){const benchmark=config.roadBenchmark||{state:'Utah',city:'Salt Lake City',road:'I-15 at 500/600 South',mean:12749.02471025585,maximum:214000,year:2024};const isUtah=/\b(UT|Utah)\b/i.test(state.overview.location);const peak=Number(benchmark.maximum||214000);const mean=Number(benchmark.mean||12749.02471025585);const share=state.ev.dailyTraffic/peak*100;const card=outlook.closest('article');if(isUtah&&peak){const label=state.ev.dailyTraffic>=mean*2?'WAY ABOVE AVERAGE':state.ev.dailyTraffic>=mean*1.1?'ABOVE AVERAGE':'AVERAGE';card.dataset.benchmarkTier=share<15?'weak':share<35?'middle':share<70?'strong':'exceptional';outlook.textContent=`${number(share,1)}% OF STATE PEAK`;card.querySelector('em').textContent=`${label} · ${number(state.ev.dailyTraffic)} / DAY HERE`;card.querySelector('small').textContent=`STATE PEAK: ${number(peak)} / DAY ON ${benchmark.road.toUpperCase()}, ${benchmark.city.toUpperCase()}, ${benchmark.state.toUpperCase()} · UDOT ${benchmark.year}.`; }else{card.dataset.benchmarkTier='pending';outlook.textContent='STATE BENCHMARK PENDING';card.querySelector('em').textContent='NO VERIFIED STATEWIDE ROADWAY PEAK CONNECTED';card.querySelector('small').textContent='A comparison tag will appear when a documented state benchmark is available.';}}
  document.querySelectorAll('.site-capture-outlook>div>b,.site-fit-card>div>b').forEach(n=>n.remove());
  const addSnapshotHelp=(selector,text)=>document.querySelectorAll(selector).forEach(node=>{if(!node.querySelector('.metric-help'))node.insertAdjacentHTML('beforeend',reviewHelp(text));});
  addSnapshotHelp('.site-capture-outlook>div>span','Source: UDOT 2024 roadway counts.\nScale: average uses the statewide mean; the state peak is 214,000 vehicles/day on I-15 in Salt Lake City, not a sales forecast.');
  addSnapshotHelp('.site-fleet-card>div>span','Source: Utah State Tax Commission registration tables.\nMethod: year-over-year BEV registrations indicate the size and growth of the local driver base.');
  addSnapshotHelp('.site-snapshot-scenario-head>span','Source: observed charging sessions, local charger inventory, and the documented EVpin forecast.\nMethod: ports, session length, and utilization produce daily visits; capture estimates potential guest parties.');
  document.querySelectorAll('.site-scenario-card>div>span').forEach(n=>{if(!n.querySelector('.metric-help'))n.insertAdjacentHTML('beforeend',reviewHelp('Source: observed charging sessions, local charger inventory, and the documented EVpin forecast.\nMethod: this scenario changes utilization while holding the proposed port count and session duration visible.'));});
  document.querySelectorAll('.site-fit-items>div').forEach(node=>{const term=node.querySelector('span');const label=term?.textContent||'';const benchmark=config.roadBenchmark||{city:'Salt Lake City',maximum:214000,mean:12749.02471025585};const help=/ROADWAY/.test(label)?'Source: UDOT 2024 roadway counts.\nScale: compares statewide average and the 214,000-vehicle/day state peak on I-15 in Salt Lake City; not a sales forecast.':/DWELL/.test(label)?'Source: independent observed charging-session data.\nMethod: average session length shows whether drivers have enough time to visit a nearby business.':/AMENIT/.test(label)?'Source: Overture Maps Places near the site.\nMethod: nearby food, restroom, and retail choices make charging time more useful to drivers.':'Source: property characteristics and site review.\nMethod: access, amenities, and circulation are practical factors that affect driver choice.';if(term&&!term.querySelector('.metric-help'))term.insertAdjacentHTML('beforeend',reviewHelp(help));if(/ROADWAY/.test(label)){const mean=Number(benchmark.mean||12749.02471025585), peak=Number(benchmark.maximum||214000), traffic=Number(state.ev.dailyTraffic);const comparison=traffic>=mean*2?'WAY ABOVE UTAH AVERAGE':traffic>=mean*1.1?'ABOVE UTAH AVERAGE':traffic>=mean*.9?'NEAR UTAH AVERAGE':traffic>=mean*.7?'SLIGHTLY LOWER THAN UTAH AVERAGE':'WELL BELOW UTAH AVERAGE';node.querySelector('strong').textContent=`${number(traffic)} / DAY`;node.querySelector('small').textContent=`${comparison} · ${number(traffic/peak*100,1)}% OF ${benchmark.city.toUpperCase()} STATE PEAK`;}});
  document.querySelectorAll('.ev-location-metric>div>span').forEach(n=>{if(!n.querySelector('.metric-help'))n.insertAdjacentHTML('beforeend',reviewHelp(/PORT/.test(n.textContent)?'Observed sessions ÷ observation days ÷ ports. This describes the measured station, not the proposed location.':/DWELL/.test(n.textContent)?'Average duration in the supplied charging-session observations.':'Successful observed sessions ÷ the number of complete observation days.'));});
  document.querySelectorAll('.visitor-meaning-card').forEach(n=>{n.classList.add('review-meaning');});
}
