import assert from 'node:assert/strict';
import fs from 'node:fs';

const app = fs.readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const catalog = JSON.parse(fs.readFileSync(new URL('../proposal-cards.json', import.meta.url), 'utf8'));

assert.match(html, /value="definitions"/);
assert.match(html, /id="definitionsView"/);
assert.match(html, />Metrics</);
assert.match(html, /Choose the proposal metrics/);
assert.match(app, /data-definition-add-toggle/);
assert.match(app, /definitionCardForTarget/);
assert.match(app, /definitionMetricModal/);
assert.match(app, /definitionExample/);
assert.match(app, /definitionDisplayGroups/);
assert.match(app, /conservativeAssumptionSource/);
assert.match(app, /definitionSourceText/);
assert.doesNotMatch(app, /\$\{cards\.length\} \$\{cards\.length === 1 \? 'metric' : 'metrics'\}/);
assert.match(app, /data-definition-choice/);
assert.match(app, /isSupplementalDefinition/);
assert.match(app, /SUPPLEMENTAL METRICS/);
assert.match(app, /Search supplemental metrics/);
assert.match(app, /definitionViewPreview/);
assert.match(app, /definitionPreviewLiveCard/);
assert.match(app, /data-archived-toggle/);
assert.match(app, /showArchived/);
assert.doesNotMatch(app, /data-definition-toggle/);
assert.match(app, /definitionIsEnabled\('locationMetrics'/);
assert.match(app, /definitionIsEnabled\('spendingCases'/);
assert.match(app, /definitionIsEnabled\('siteSnapshotMockup\.scenarios'/);
assert.match(app, /definitionIsEnabled\('financialCards\.chargingRevenue'/);
assert.match(app, /definitionIsEnabled\('financialCards\.expenses'/);
assert.match(app, /definitionIsEnabled\('referencePages\.about\.cards'/);
assert.match(app, /persistDefinitions\(\)/);
assert.doesNotMatch(html, /id="addDefinitionCard"/);
assert.doesNotMatch(html, /data-definition-field/);
assert.doesNotMatch(html, /Suggestions appear when you type/);
assert.doesNotMatch(app, />REPORT SECTION</);
assert.match(app, /definitionsStorageKey.*copiedProposal/);
assert.match(app, /copiedProposal\.copyId \|\| 'copy'/);
assert.match(app, /copyId: `proposal-\$\{Date\.now\(\)\}`/);
assert.doesNotMatch(app, /label: 'NEW MARKET METRIC'/);
assert.ok(catalog.ev.locationMetrics.every(card => card.label && (card.valueId || card.receiptId)));
assert.ok(catalog.ev.spendingCases.every(card => card.label && card.receiptId && card.source));
assert.ok(catalog.ev.financialCards.chargingRevenue.every(card => card.label && card.valueId));
assert.ok(catalog.ev.financialCards.expenses.every(card => card.label && card.valueId));
assert.ok(catalog.ev.portfolioMetrics.storeBreakdown.length >= 20);
assert.ok(catalog.ev.portfolioMetrics.scorecard.length >= 6);
assert.ok(catalog.ev.portfolioMetrics.utilization.length >= 8);
assert.ok(catalog.ev.portfolioMetrics.financing.length >= 4);
assert.ok(catalog.ev.portfolioMetrics.lease.length >= 6);
assert.ok(catalog.ev.portfolioMetrics.fieldGuide.length >= 4);
assert.ok(catalog.ev.portfolioMetrics.fields.length >= 15);
assert.match(app, /portfolioMetrics\.storeBreakdown/);
assert.match(app, /portfolioMetrics\.scorecard/);
assert.match(app, /portfolioMetrics\.utilization/);
assert.match(app, /portfolioMetrics\.financing/);
assert.match(app, /portfolioMetrics\.lease/);
assert.match(app, /portfolioMetrics\.fieldGuide/);
assert.match(app, /portfolioMetrics\.fields/);
console.log('definitions acceptance checks passed');
